### PR TITLE
WAK-Bugfixes-Early-December

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Comment by captaincobbs** [comment]
It's the time of giving

**Comment by captaincobbs** [comment]
Your poor indentation displeases me

**Comment by wakystuf** [comment]
I looked at the indentation and it seems fine in VS Code. Which files are messed up? Maybe VS Code is lying...

**Comment by captaincobbs** [comment]
VS code displays 2 space tabs and 4 space tabs identically, but:
Endless Space Competitive Mod/GUI/GUIElements[EntityAction].xml
 Endless Space Competitive Mod/Simulation/SimulationDescriptors[LawEffectsT0].xml

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
