### PR TITLE
Craver Terraformation Module Science from Depletion scale with Game Speed

### PR DESCRIPTION
**Pull request by ThanosDeGraf**

### CODE REVIEW

**Review by captaincobbs — APPROVED** [review]
Looks good to me, I'll let waky merge it

**Comment by ThanosDeGraf** [comment]
Please see #966

**Comment by wakystuf** [comment]
Does this actually work in testing? It looks like you created a variable in ClassModuleWeapon, pushed the value into ALL modules, and then referenced the variable in support modules, right? I would surprised if that functioned as intended

**Comment by ThanosDeGraf** [comment]
It really worked. On endless speed, Husk has about 200 depletion points already, but the module itself gives the intended 50 science instead of 100.  it seems like support modules is part of modules, so I was able to reference it.

**Comment by Provolonage** [comment]
also we should not apply this to any other module it will literally break the game balance, we dont want other support modules scaling with game speed.

**Comment by ThanosDeGraf** [comment]
I had to manually go into the formula for EmpireSciencePerDepletionPoint and have it inversely scale with GameSpeedMultiplier. I'm sure anybody sensible enough would catch somebody trying to do some game speed on module shenanigans. But as it is rn, it seems pretty safe since this is the first time a module uses game speed.

I agree that this should be handled with care and that this is a big exception. It had to be done, since as you know planets have a bigger depletion point cap in slower gamespeeds, meaning higher science output with slower speeds, and worse output on fast. It's mearly implement to offset this, and any given system should now produce the same maximum amount of science for different gamespeeds.

**Comment by captaincobbs** [comment]
I advised him to push the GameSpeedMultiplier into ClassModule, since it seems to be used for a few other special cases I deemed that it'd be more effective to have one modifier, rather than 4 or so different modifiers forcing the same value after searching through every module 4 times. This doesn't affect anything other than put the variable into the Class.

**Comment by captaincobbs** [comment]
@wakystuf I'm going to go ahead and merge this, he's shown me proof everything works properly and that there are no conflicts.

**Comment by wakystuf** [comment]
Won't the removal of GameSpeedMultiplier break all the mining probes? It looks like the code is still looking for that exact variable, right?

**Comment by wakystuf** [comment]
I see now; I thought the newly added variable had a different name (maybe I'm remembering an older version of the code when he DM'd it to me), but it looks like they match so it should be fine.

**Comment by ThanosDeGraf** [comment]
Yea, before I called it something like EmpireResearchPerDepletionPointAdjuster, but then Cobbs told me it's perfectly fine to call these Properties the same.

**Pull request merged**
