### PR TITLE
Diplomacy Rework

### PR DESCRIPTION
**Pull request by captaincobbs**

### CODE REVIEW

**Comment by captaincobbs** [comment]
lmao this pull request is gonna be a nightmare

**Comment by wakystuf** [comment]
Yeah, it looks like you drafted the request to merge into Main; was that intentional? Will it break anything to simply close this PR and create a new one to merge the branch into Development?

Alternately, I might just manually migrate stuff over, since I don't want to accidentally do a reverse of "the big merge"

**Comment by captaincobbs** [comment]
Oops not intentional

**Comment by wakystuf** [comment]
OK, I will fix everything, and make sure that the related commit names make fun of you.

**Pull request closed without merging**
