### PR TITLE
Propaganda fix

### PR DESCRIPTION
**Pull request by ThanosDeGraf**

### CODE REVIEW

**Comment by wakystuf** [comment]
This looks like it should work, but does the alternate unconditional version show up in addition to the conditional version once you've unlocked both techs?

**Comment by ThanosDeGraf** [comment]
It's set up so the conditional versions get disabled when slc is unlocked, so you want have twice militarist or ecologist propaganda. I can test it again in a moment.

**Comment by ThanosDeGraf** [comment]
image
image

Working as intended.

**Comment by ThanosDeGraf** [comment]
If you'd like, we can wait a little with this merge and you (waky) and I can do some of the propaganda rework on here?

**Comment by wakystuf** [comment]
Ah, I see. I'll merge now

**Review by wakystuf — APPROVED** [review]

**Pull request merged**
