### PR TITLE
Updated Terraforming Costs for Unfallen Unique Terraforming

### PR DESCRIPTION
**Pull request by ThanosDeGraf**

### CODE REVIEW

**Comment by ThanosDeGraf** [comment]
I'd like to talk with cobbs about adding the oddly missing terraforming options before the merge though.

**Comment by wakystuf** [comment]
This looks good, but remember you need to also do it in the other files, right? Like in [Vanilla], [Free], etc

**Comment by ThanosDeGraf** [comment]
It's weird, for example PlanetTerraformationFromDesertToForest does not appear anywhere but in [Vanilla] and [Unique].

**Comment by wakystuf** [comment]
Hmm... @captaincobbs do you know why that is?

**Comment by captaincobbs** [comment]
Why would it be in free terraformation or gas terraformation?

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
