### PR TITLE
WAK-changes-Jan

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Comment by captaincobbs** [comment]
You should scale things like the behemoth modules, deposit population bonuses, and mining buildings

**Comment by wakystuf** [comment]
We decided not to scale the behemoth modules. The other stuff should all already be scaled by this change. Miner's Union was th one I was testing with and it scaled just fine

**Comment by captaincobbs** [comment]
does it just scale the deposit value, or does it actually do the tooltips?

**Comment by wakystuf** [comment]
It shows up properly in the GUI for the amount being mined, if that's what you mean

**Comment by captaincobbs** [comment]
I mean the building and population tooltips

**Comment by captaincobbs** [comment]
(not the deposit tooltip)

**Comment by wakystuf** [comment]
Oh, I didn't mess with those

**Comment by captaincobbs** [comment]
Do it please, make an extended gui element, with a tooltip element that has a "CustomTurnDuration", and then an effect override. Check LawEffectP01L01_ESG for an example. Doesn't work with decimals like 0.5 or 1.5 though.
If it's guaranteed to be a decimal that doesn't go above one, I usually do something like CustomTurnDuration="20", then set the tooltip override to "0.{0} Deposit Value Bonus"

**Comment by wakystuf** [comment]
@Provolonage  you hear that? 😉

**Pull request merged**
