### PR TITLE
Dictatorship-Buffs

### PR DESCRIPTION
**Pull request by wakystuf**

### CODE REVIEW

**Comment by wakystuf** [comment]
Works.
@Arpharnator let me know if there are any changes you would suggest and we can incorporate

**Review by captaincobbs — COMMENTED** [review]
Are we going to add lowered enaction costs?

**Comment by wakystuf** [comment]
I'd rather not, for a few reasons:
1) That feels like a Democracy mechanic so I'd rather keep it separate
2) They still have to afford the upkeeps, so lower enaction is only mildly helpful
3) Dictatorship factions (by coincidence) all produce decent influence and should mostly be fiine
4) The best thing about this tbh might be getting access to the higher-tier independent laws earlier, which don't require influence

**Comment by captaincobbs** [comment]
1. Doesn't democracy get lowered upkeep instead? I don't feel like it'd overlap.
2. But they lose flexibility because they have to pay for more enaction costs more often than any other government types
3. That is true, but I still feel like without lowered enaction costs it will just be more annoying than helpful
4. I agree

**Comment by wakystuf** [comment]
1. Correct, Democracy gets lower upkeep; I just think the 2 things are like very similar though you're correct that they aren't identical
2. Oh, I see what you're getting at now (this idea that dictatorships will be changing laws more often). I think I mostly disagree with that premise, though you're correct that this change will make them more inclined to change laws than they did before:
2a: I suspect most dictatorships will not use this ability to switch around constantly (though they made do that sometimes); it's more about going deeper into their chosen political party more rapidly. 
2b: By virtue of only having access to 1 party's laws at a time (excluding independents), they have less incentive/ability to constantly rearrange. Meanwhile, the UC are frequently swapping between diplo cost reductions, faster probe regen, lower buildings costs, etc, because they have many more options. (I think basically every government with scientist should spent the early game toggling Dirty Hands on and off, since it is only valuable when you're about to finish a building)

By the way, I told Arphar that I was willing to remove the +1 action point and move that to a tech IF he could come up with something better (and that offer still stands), but if not then we'd use these.

**Comment by captaincobbs** [comment]
If the extra action point if still kept, I'm fine with it just being moved to a tech. I agree with what you're saying though, except for your first point. It's not a big deal though, so I'll just accept.

**Review by captaincobbs — APPROVED** [review]

**Pull request merged**
